webtalk_init -webtalk_dir C:/Users/Timothy/Desktop/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/zero_sequence_detector_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 22 20:46:36 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea205d1d-5a00-477e-b103-aaf353adac65" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b9a8d5e40884c3d9939f2dec87e467d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "210 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9920_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2631247806 -regid "" -xml C:/Users/Timothy/Desktop/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/zero_sequence_detector_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Timothy/Desktop/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/zero_sequence_detector_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Timothy/Desktop/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/zero_sequence_detector_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
